In [1]:
#图1.58
import numpy as np #导入numpy库并按惯例将其重命名为np

In [2]:
#图1.59
a_python_list=[1,2]
a_numpy_array=np.array([1,2])
type(a_python_list),type(a_numpy_array)#二者类型不一样

(list, numpy.ndarray)

In [5]:
#图1.60
a_python_list*2,a_numpy_array*2 #乘以2的结果也不一样

([1, 2, 1, 2], array([2, 4]))

In [6]:
#图1.61
a_python_list.append(3)
a_python_list

[1, 2, 3]

In [7]:
#np.array不支持添加元素
try:
    a_numpy_array.append(3)
except Exception as e:
    print(str(e))

'numpy.ndarray' object has no attribute 'append'


In [9]:
#图1.62
#二者可以互换
a=np.array(a_python_list)
b=list(a)
a,b

(array([1, 2, 3]), [1, 2, 3])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.arange(1,10,2) #不包含10

array([1, 3, 5, 7, 9])

In [14]:
np.linspace(1,10,5) #绘图时经常使用这个函数,包含10

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [15]:
np.arange(16).reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
x=np.arange(1,5).reshape((2,2))
x

array([[1, 2],
       [3, 4]])

In [17]:
y=np.arange(5,9).reshape((2,2))
y

array([[5, 6],
       [7, 8]])

In [19]:
x+y

array([[ 6,  8],
       [10, 12]])

In [20]:
x-y

array([[-4, -4],
       [-4, -4]])

In [21]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [22]:
x*y

array([[ 5, 12],
       [21, 32]])

In [23]:
np.sqrt(x) #所有元素取平方根

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [24]:
np.log(x) #所有元素取自然对数

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [25]:
np.sin(x) #所有元素取正弦

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [26]:
np.cos(x)  #所有元素取余弦

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [27]:
100+x #np特有的广播机制

array([[101, 102],
       [103, 104]])

In [28]:
#图1.63
a=[1,2,3]
try:
    a=a+1 #这行代码将出现异常，list不支持这种操作
except Exception as e:
    print('异常信息:{}'.format(str(e)))
finally:
    print(np.array(a)+1)

异常信息:can only concatenate list (not "int") to list
[2 3 4]
