In [1]:
#例29.1

In [2]:
def factorial(n):
    if n==0:return 1
    return n*factorial(n-1)
factorial(5)

120

In [3]:
#例29.2

In [4]:
import numpy as np 
def I(n):
    if n==0:return np.pi/2
    if n==1:return 1
    return (n-1)*I(n-2)/n
I(1),I(2),I(3)

(1, 0.7853981633974483, 0.6666666666666666)

In [5]:
#例29.3

In [6]:
def F(n):
    if n<=2:return n
    return F(n-1)+F(n-2)
for i in range(1,11):
    print(F(i),end=';')

1;2;3;5;8;13;21;34;55;89;

In [7]:
#例29.4

In [8]:
def C(n,m):
    if n==m or m==0:return 1
    return C(n-1,m)+C(n-1,m-1)
C(10,5)

252

In [9]:
#例29.5

In [10]:
#最短路径问题

In [11]:
a=np.ones((16,16))*100.0
a[0][1]=5
a[0][2]=3
a[1][3]=1
a[1][4]=3
a[1][5]=6
a[2][4]=8
a[2][5]=7
a[2][6]=6
a[3][7]=6
a[3][8]=8
a[4][7]=3
a[4][8]=5
a[5][8]=3
a[5][9]=3
a[6][8]=8
a[6][9]=4
a[7][10]=2
a[7][11]=2
a[8][11]=1
a[8][12]=2
a[9][11]=3
a[9][12]=3
a[10][13]=3
a[10][14]=5
a[11][13]=5
a[11][14]=2
a[12][13]=6
a[12][14]=6
a[13][15]=4
a[14][15]=3

In [12]:
def minDistance(idxPoint,max_point_idx=15):
    if idxPoint>=max_point_idx:
        return 0
    b=[]
    for col in range(max_point_idx+1):
        if a[idxPoint][col]>99:
            continue
        b.append(a[idxPoint,col]+minDistance(col))
    return np.min(np.array(b))

minDistance(0)

18.0

In [13]:
points=['A','B1','B2','C1','C2','C3','C4','D1','D2','D3','E1','E2','E3','F1','F2','G']
while True:
    B=np.random.randint(1,3)
    C=np.random.randint(3,7)
    D=np.random.randint(7,10)
    E=np.random.randint(10,13)
    F=np.random.randint(13,15)
    if a[0][B]+a[B][C]+a[C][D]+a[D][E]+a[E][F]+a[F][15]==18:
        print('The shortest path is:\tA->{}->{}->{}->{}->{}->G'.format(points[B],points[C],points[D],points[E],points[F]))
        break

The shortest path is:	A->B1->C2->D1->E2->F2->G


In [14]:
#例29.6

In [15]:
from scipy.optimize import minimize
def fun(x,sign=1.0):
    return sign*(x[0]*x[1]**2*x[2])
cons=({'type':'eq','fun':lambda x:np.array([x[0]+x[1]+x[2]-1])},
      {'type':'ineq','fun':lambda x:np.array([x[0]])},
      {'type':'ineq','fun':lambda x:np.array([x[1]])},
      {'type':'ineq','fun':lambda x:np.array([x[2]])})
result=minimize(fun,[0.3,0.3,0.3],args=(-1.0,),constraints=cons)
x=np.round(result.x,5)
x,fun(x)

(array([0.24923, 0.50153, 0.24923]), 0.015624080488528423)

In [16]:
#例29.7

In [17]:
def fun(x,sign=1.0):
    return sign*(4*x[0]**2-x[1]**2+2*x[2]**2+12)
cons=({'type':'ineq','fun':lambda x:np.array([-3*x[0]-2*x[1]-x[2]+9])},
      {'type':'ineq','fun':lambda x:np.array([x[0]])},
      {'type':'ineq','fun':lambda x:np.array([x[1]])},
      {'type':'ineq','fun':lambda x:np.array([x[2]])})
result=minimize(fun,[1,1,1],args=(-1.0,),constraints=cons)
x=np.round(result.x,3)
x,fun(x)

(array([-0.,  0.,  9.]), 174.0)

In [18]:
def fun(x,sign=1.0):
    return sign*(4*x[0]**2-x[1]**2+2*x[2]**2+12)
cons=({'type':'ineq','fun':lambda x:np.array([-3*x[0]-2*x[1]-x[2]+9])},
      {'type':'ineq','fun':lambda x:np.array([x[0]])},
      {'type':'ineq','fun':lambda x:np.array([x[1]])},
      {'type':'ineq','fun':lambda x:np.array([x[2]])})
result=minimize(fun,[0,0,0],args=(-1.0,),constraints=cons)
x=np.round(result.x,3)
x,fun(x)

(array([0., 0., 0.]), 12.0)