In [1]:
import numpy as np
from scipy.optimize import minimize

In [2]:
#例28.1

In [3]:
def f(x,sign=1.0):return sign*(8*x[0]+10*x[1]-x[0]**2-x[1]**2)
cons=(
    {'type':'ineq','fun':lambda x:np.array([6-3*x[0]-2*x[1]])},
    {'type':'ineq','fun':lambda x:np.array([x[0]])},
    {'type':'ineq','fun':lambda x:np.array([x[1]])}
    )
result=minimize(f,[100,100],args=(-1.0,),constraints=cons)
x=result.x
x,f(x)

(array([0.30769233, 2.53846151]), 21.30769230769193)

In [4]:
#例28.2

In [5]:
def f(x,sign=1.0):return sign*(4*x[0]+4*x[1]-x[0]**2-x[1]**2)
cons=(
    {'type':'ineq','fun':lambda x:np.array([4-x[0]-2*x[1]])}
    )
result=minimize(f,[100,100],args=(-1.0,),constraints=cons)
result.x,np.round(result.fun,3)

(array([1.59999999, 1.2       ]), -7.2)

In [6]:
#例28.3

In [7]:
def f(x,sign=1.0):
    return sign*((x[0]+1)**3/3+x[1])
cons=({'type':'ineq','fun':lambda x:np.array([x[0]-1])},
      {'type':'ineq','fun':lambda x:np.array([x[1]])})
result=minimize(f,[50,-50],constraints=cons)
np.round(result.x,3),np.round(result.fun,3)

(array([1., 0.]), 2.667)