In [1]:
import numpy as np
from scipy.optimize import linprog

In [2]:
#例25.1

In [3]:
c=np.array([8,10])
A=np.array([[2,1],[1,2]])
b=np.array([11,10])
c=-c
result=linprog(c,A_ub=A,b_ub=b)
-result.fun.round(3),result.x.round(3)

(62.0, array([4., 3.]))

In [4]:
#例25.2

In [5]:
c=np.array([0,0,0,8,0,4,2,2,1,0])
A_eq=np.array([
               [1,-1,1,-1,0,0,0,0,0,0],
               [2,1,0,0,1,-1,0,0,0,0],
               [1,2,0,0,0,0,1,-1,0,0],
               [8,10,0,0,0,0,0,0,1,-1]
              ])
b_eq=np.array([0,11,10,56])
result=linprog(c,A_eq=A_eq,b_eq=b_eq,method='simplex')
result.x.round(3),result.fun

(array([2., 4., 2., 0., 3., 0., 0., 0., 0., 0.]), 0.0)

In [6]:
#例25.3

In [7]:
c=np.array([0,0,8,0,0,4,2,0,1,0])
A_eq=np.array([
                [1,1,1,-1,0,0,0,0,0,0],
                [1,1,0,0,1,-1,0,0,0,0],
                [1,0,0,0,0,0,1,-1,0,0],
                [0,1,0,0,0,0,0,0,1,-1]
              ])
b_eq=np.array([40,50,24,30])
result=linprog(c,A_eq=A_eq,b_eq=b_eq)
result.x.round(3),result.fun.round(3)

(array([24., 26.,  0., 10.,  0.,  0.,  0.,  0.,  4.,  0.]), 4.0)

In [8]:
#例25.4

In [9]:
priority=np.array([0,0,0,0,4,0,2,0,2,0,2,1,0,1,0])
left_x=np.array([
                [2.5,2.5,5],
                [1,0,0],
                [-1,1,0],
                [0,-1,1],
                [1,0,0],
                [0,1,0]
             ])
right_d=np.array([
                [1,-1,0,0,0,0,0,0,0,0,0,0],
                [0,0,1,-1,0,0,0,0,0,0,0,0],
                [0,0,0,0,1,-1,0,0,0,0,0,0],
                [0,0,0,0,0,0,1,-1,0,0,0,0],
                [0,0,0,0,0,0,0,0,1,-1,0,0],
                [0,0,0,0,0,0,0,0,0,0,1,-1]
              ])
#np.hstack((A,B))将两个行数相同的数组在水平方向上拼接
A_eq=np.hstack((left_x,right_d))
b_eq=np.array([450,30,30,0,24,30])
result=linprog(priority,A_eq=A_eq,b_eq=b_eq,method='simplex')
print(result.fun.round(3))
result.x.round(3)

0.0


array([24., 52., 52.,  0.,  0.,  6.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,
        0., 22.])

In [10]:
import pulp
m=pulp.LpProblem(sense=pulp.LpMinimize)
x=[pulp.LpVariable(f'x{i}',lowBound=0,cat=pulp.LpInteger)\
     for i in np.arange(1,16)]
m+=pulp.lpDot(priority,x)
for i in np.arange(6):
    m+=(pulp.lpDot(A_eq[i],x)==b_eq[i])
m.solve()
print(pulp.value(m.objective))
print([pulp.value(var) for var in x])

0.0
[24.0, 30.0, 0.0, 315.0, 0.0, 6.0, 0.0, 24.0, 0.0, 30.0, 0.0, 0.0, 0.0, 0.0, 0.0]


In [11]:
#例25.5

In [12]:
# 首先求出此问题的最小运费
m=pulp.LpProblem()
c=[[5,2,6,7],[3,5,4,6],[4,5,2,3]]
production=[300,200,400]
requirement=[200,100,450,250]
x=[[pulp.LpVariable(f'{i}{j}',lowBound=0,cat=pulp.LpInteger) \
    for j in range(4)] for i in range(3)]
m+=sum([pulp.lpDot(c[row],x[row]) for row in range(3)])
for row in range(3):
    m+=(sum(x[row])==production[row])
x_T=np.array(x).T
for col in range(4):
    m+=(sum(x_T[col])<=requirement[col])
m.solve()
pulp.value(m.objective)

2950.0

In [13]:
#价值向量
c=np.zeros(38)
c[18]=64
c[20]=32
c[22]=16
c[24]=16
c[26]=16
c[28]=16
c[31]=8
c[33]=4
c[34]=2
c[35]=2
c[37]=1

#等式约束矩阵
A=np.zeros((16,38))
A[0][:4]=1
A[1][4:8]=1
A[2][8:12]=1
#A[3]
A[3][0]=1
A[3][4]=1
A[3][8]=1
A[3][12]=1
A[3][13]=-1
#A[4]
A[4][1]=1
A[4][5]=1
A[4][9]=1
A[4][14]=1
A[4][15]=-1
#A[5]
A[5][2]=1
A[5][6]=1
A[5][10]=1
A[5][16]=1
A[5][17]=-1
#A[6]
A[6][3]=1
A[6][7]=1
A[6][11]=1
A[6][18]=1
A[6][19]=-1
#A[7]
A[7][8]=1
A[7][20]=1
A[7][21]=-1
#A[8]
A[8][0]=1
A[8][4]=1
A[8][8]=1
A[8][22]=1
A[8][23]=-1
#A[9]
A[9][1]=1
A[9][5]=1
A[9][9]=1
A[9][24]=1
A[9][25]=-1
#A[10]
A[10][2]=1
A[10][6]=1
A[10][10]=1
A[10][26]=1
A[10][27]=-1
#A[11]
A[11][3]=1
A[11][7]=1
A[11][11]=1
A[11][28]=1
A[11][29]=-1
#A[12]
A[12][0:12]=[5,2,6,7,3,5,4,6,4,5,2,3]
A[12][30]=1
A[12][31]=-1
#A[13]
A[13][7]=1
A[13][32]=1
A[13][33]=-1
#A[14]
A[14][0]=1
A[14][4]=1
A[14][8]=1
A[14][2]=-200/450
A[14][6]=-200/450
A[14][10]=-200/450
A[14][34]=1
A[14][35]=-1
#A[15]
A[15][:12]=[5,2,6,7,3,5,4,6,4,5,2,3]
A[15][36]=1
A[15][37]=-1

#资源向量
b=np.array([300,200,400,200,100,450,250,100,\
    160,80,360,200,2950*1.1,0,0,2950])

In [14]:
m=pulp.LpProblem()
x=[pulp.LpVariable(f'x{i}',lowBound=0,cat=pulp.LpInteger) \
    for i in range(38)]
m+=pulp.lpDot(c,x)
for i in np.arange(16):
    m+=(pulp.lpDot(A[i],x)==b[i])
m.solve()
result_x=[pulp.value(x[i]) for i in range(12)]
result_d=[pulp.value(x[i]) for i in range(12,38)]
result_x=np.array(result_x).reshape((3,4))
result_d=np.array(result_d).reshape((13,2))
print('x is:')
print(result_x)
print('=====================')
print('d is:')
print(result_d)
print('===========')
print('z is:')
print(pulp.value(m.objective))

x is:
[[  0. 139. 161.   0.]
 [ 60.   0. 140.   0.]
 [100.   0.  50. 250.]]
d is:
[[ 40.   0.]
 [  0.  39.]
 [ 99.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.  59.]
 [  9.   0.]
 [  0.  50.]
 [ 11.   0.]
 [  0.   0.]
 [  0.   4.]
 [  0. 284.]]
z is:
436.0


In [15]:
# linprog求解
result=linprog(c,A_eq=A,b_eq=b)
res=np.array(result.x[:12]).round(0).reshape((3,4))
res,result.fun.round(0)

(array([[ 29., 136.,  70.,  65.],
        [ 31.,   0., 169.,   0.],
        [100.,   0., 115., 185.]]), 401.0)