In [1]:
import numpy as np

In [2]:
def Dijkstra(fromIdx,endIdx,adjacentMatrix,M=100000,iterAll=False):
    """
    参数：
        fromIdx:起始点索引
        endIdx:终点索引
        adjacentMatrix:邻接矩阵
        M:非相邻顶点的距离
        iterAll:是否遍历所有顶点，默认False(当添加endIdx信息后停止遍历剩余顶点)
    返回：
        distanceArray：距起始顶点的距离数组
        parentArray：顶点的父顶点索引数组
    """
    lenMatrix=len(adjacentMatrix)
    #保存已标注的顶点
    T=[]
    #保存未标注的顶点
    N_T=[]
    for idx in range(lenMatrix):
        N_T.append(idx)
    T.append(fromIdx)
    N_T.remove(fromIdx)
    #保存顶点endIdx至初始顶点fromIdx的最短路径上的每一顶点至fromIdx的最短距离
    distanceArray=np.ones(lenMatrix)*M
    distanceArray[fromIdx]=0
    #保存顶点endIdx至初始顶点fromIdx的最短路径上的每一顶点的父（上一）顶点的索引，初始值均为-1
    parentArray=np.ones(lenMatrix)*(-1)
    while True: 
        if endIdx in T and not iterAll:
            break
        if len(T)==lenMatrix:
            break
        storageDistance=[]
        storageIndex=[]
        storageParentIndex=[]
        #在未标注的顶点中查找离已标注顶点距离最近的顶点
        for point in T:
            temp=[]
            for nextPoint in range(lenMatrix):
                temp.append(M if nextPoint in T else adjacentMatrix[point][nextPoint])
            minDistance=np.min(temp)
            #np.argmin(temp)获得列表temp的最小元素的索引
            minIdx=np.argmin(temp)
            storageDistance.append(minDistance+distanceArray[point])
            storageIndex.append(minIdx)
            storageParentIndex.append(point)
        minDistance_fromIdx=np.min(storageDistance)
        minDistance_Index=np.argmin(storageDistance)
        #在列表T中添加已标注顶点，并在N_T中删除这个顶点
        if minDistance_fromIdx<M:
            appendIndex=storageIndex[minDistance_Index]
            T.append(appendIndex)
            N_T.remove(appendIndex)
            distanceArray[appendIndex]=minDistance_fromIdx
            parentArray[appendIndex]=storageParentIndex[minDistance_Index]
        #所有的顶点都已标注，退出while循环
        else:
            break
    return distanceArray,parentArray

In [3]:
#例31.1

In [4]:
M=100
matrix=np.array([
                [0,6,3,1,M,M,M,M,M],
                [6,0,2,M,1,M,M,M,M],
                [3,2,0,2,M,M,M,M,M],
                [1,M,2,0,6,10,M,M,M],
                [M,1,M,6,0,4,3,6,2],
                [M,M,M,10,4,0,2,M,M],
                [M,M,M,M,3,2,0,4,M],
                [M,M,M,M,6,M,4,0,3],
                [M,M,M,M,2,M,M,3,0]
                ])
fromIdx=0
endIdx=7
distance,parent=Dijkstra(fromIdx,endIdx,matrix,M=M)
distance,parent

(array([ 0.,  5.,  3.,  1.,  6., 10.,  9., 11.,  8.]),
 array([-1.,  2.,  0.,  0.,  1.,  4.,  4.,  8.,  4.]))

In [5]:
vertexes=['v1','v2','v3','v4','v5','v6','v7','v8','v9']
end_idx=endIdx
print('The shortest distance from \'{}\' to \'{}\' is {},the path is:'.format(vertexes[fromIdx],vertexes[end_idx],distance[end_idx]),            end=' ')
path=[]
path.append(vertexes[end_idx])
while end_idx!=fromIdx and end_idx>-1:
    end_idx=int(parent[end_idx])
    path.append(vertexes[end_idx])
path.reverse()
print(path)

The shortest distance from 'v1' to 'v8' is 11.0,the path is: ['v1', 'v3', 'v2', 'v5', 'v9', 'v8']


In [6]:
def minDistance_with_neg_arc(fromIdx,adjacentMatrix,M=100000):
    """
    参数：
        fromIdx:起始顶点索引
        adjacentMatrix:邻接矩阵
        M:非相邻顶点的距离
    返回值：
        success:是否计算成功(如果图中含有负回路，则计算失败)
        A:自起始顶点至各顶点的最短距离数组
    """
    lenMatrix=len(adjacentMatrix)
    A=adjacentMatrix[fromIdx]
    B=[M]*lenMatrix
    maxEdges=1
    success=True
    while A!=B:
        for i in range(lenMatrix):
            temp=[]
            for j in range(lenMatrix):
                x=A[j]+adjacentMatrix[j][i] 
                if x>=M/2:x=M
                temp.append(x)
            B[i]=min(temp)
        A,B=B,A
        maxEdges+=1
        if maxEdges>=lenMatrix:
            success=False
            break
    return success,A

In [7]:
#例31.2

In [8]:
#最短路径问题
M=100000
disMatrix=[
           [0,-1,-2,3,M,M,M,M],
           [6,0,M,M,2,M,M,M],
           [M,-3,0,-5,M,1,M,M],
           [8,M,M,0,M,M,2,M],
           [M,-1,M,M,0,M,M,M],
           [M,M,M,M,1,0,1,7],
           [M,M,M,-1,M,M,0,M],
           [M,M,M,M,-3,M,-5,0]
          ]
success,A=minDistance_with_neg_arc(0,disMatrix)
success,A

(True, [0, -5, -2, -7, -3, -1, -5, 6])

In [9]:
#例31.3

In [10]:
#设备更新问题
M=1000
adM=np.ones((6,6))*M
adM[0][1]=16
adM[0][2]=22
adM[0][3]=30
adM[0][4]=41
adM[0][5]=59
adM[1][2]=16
adM[1][3]=22
adM[1][4]=30
adM[1][5]=41
adM[2][3]=17
adM[2][4]=23
adM[2][5]=31
adM[3][4]=17
adM[3][5]=23
adM[4][5]=18
fromIdx=0
endIdx=5
disArr,parArr=Dijkstra(fromIdx,endIdx,adM,M=M)
disArr,parArr

(array([ 0., 16., 22., 30., 41., 53.]), array([-1.,  0.,  0.,  0.,  0.,  2.]))

In [11]:
#设备更新问题的随机模拟方法
np.random.seed(0)
minCost=M
for _ in range(50):
    project=[0]
    cost=0
    while True:
        a=np.random.randint(1,6)
        project.append(a)
        if a==5:
            project.sort()
            for idx in range(len(set(project))-1):
                cost+=adM[project[idx]][project[idx+1]]
            if cost<=minCost:
                print(project,cost)
                minCost=cost
            break

[0, 5] 59.0
[0, 1, 5] 57.0
[0, 2, 5] 53.0
[0, 3, 5] 53.0


In [12]:
#例31.4

In [13]:
#网络最大流的线性规划解法
from scipy.optimize import linprog
#价值向量
c=np.array([-1,-1,0,0,0,0,0,0,0])
#9行9列的单位矩阵
Aub=np.eye(9)
bub=np.array([3,5,1,4,2,1,3,5,2])
#等式约束矩阵
Aeq=np.array([
                [1,1,0,0,0,0,0,-1,-1],
                [0,1,1,0,-1,0,0,0,0],
                [1,0,-1,-1,0,1,0,0,0],
                [0,0,0,1,0,0,1,-1,0],
                [0,0,0,0,1,-1,-1,0,-1]
            ])
beq=np.array([0]*5)
result=linprog(c,A_ub=Aub,b_ub=bub,A_eq=Aeq,b_eq=beq,method='simplex')
np.round(-result.fun,3),np.round(result.x,3)

(5.0, array([3., 2., 0., 3., 2., 0., 0., 3., 2.]))

In [14]:
MaxFlow=np.zeros((5,6,2))
MaxFlow[0][1][0]=5
MaxFlow[0][2][0]=3
MaxFlow[1][3][0]=2
MaxFlow[2][1][0]=1
MaxFlow[2][4][0]=4
MaxFlow[3][2][0]=1
MaxFlow[3][4][0]=3
MaxFlow[3][5][0]=2
MaxFlow[4][5][0]=5

In [15]:
#随机获得一条从起点至终点的路径
def find_path(max_flow,max_search_times=10000):
    success=False
    from_idx=0
    path=[from_idx]
    search_times=0
    while search_times<max_search_times:
        next_vertexes=[index for index in range(len(max_flow[0])) if max_flow[from_idx][index][0]>max_flow[from_idx][index][1]]
        if len(next_vertexes)==0:
            search_times+=1
            from_idx=fromIdx
            continue
        next_vertex=next_vertexes[np.random.randint(len(next_vertexes))]
        path.append(next_vertex)
        if next_vertex==len(max_flow[0])-1:
            success=True
            break
        from_idx=next_vertex
    if success:
        for i in range(len(path)-1,0,-1):
            if path[i] in path[:i]:
                #去除路径中的圈
                path.remove(path[i])
        return path
    else:return []

In [16]:
find_path(MaxFlow)

[0, 1, 3, 5]

In [17]:
#用随机模拟方法查看有向图中是否有圈
def find_circle(max_flow,max_search_times=100):
    hasCircle=False
    minVetex_idx=1
    maxVetex_idx=len(max_flow[0])-2
    for idx in range(minVetex_idx,maxVetex_idx+1):
        path=[idx]
        distance=[]
        search_times=0
        from_idx=idx
        while search_times<max_search_times:
            next_vertexes=[index for index in range(minVetex_idx,maxVetex_idx+1) if max_flow[from_idx][index][1]>0]
            if len(next_vertexes)==0:
                path=[idx]
                distance=[]
                search_times+=1
                from_idx=idx
                continue
            next_vertex=next_vertexes[np.random.randint(len(next_vertexes))]
            path.append(next_vertex)
            distance.append(max_flow[from_idx][next_vertex][1])
            if next_vertex==idx:
                hasCircle=True
                min_dis=min(distance)
                for i in range(len(path)-1):
                    max_flow[path[i]][path[i+1]][1]=max_flow[path[i]][path[i+1]][1]-min_dis
                return hasCircle
            from_idx=next_vertex
    return hasCircle

In [18]:
testFlow=np.zeros((5,6,2))
testFlow[0][1]=[5,1]
testFlow[0][2]=[3,1]
testFlow[1][3]=[2,2]
testFlow[2][1]=[1,1]
testFlow[2][4]=[4,1]
testFlow[3][2]=[1,1]
testFlow[3][5]=[2,1]
testFlow[4][5]=[5,1]
print(find_circle(testFlow))

True


In [19]:
#网络最大流函数，返回网络最大流和对应顶点、边的索引及流量及信息
def max_net_flow(max_flow):   
    while True:
        path=find_path(max_flow)
        if len(path)==0:
            if find_circle(max_flow):continue
            S=set()
            for row in range(len(max_flow)):
                for col in range(len(max_flow[0])):
                    if max_flow[row][col][0]>0:
                        S.add((row,col,max_flow[row][col][1]))
            return sum(max_flow[0])[1],S
        flowArr=[]
        for i in range(len(path)-1):
            appendFlow=max_flow[path[i]][path[i+1]][0]-max_flow[path[i]][path[i+1]][1] if path[i]<path[i+1]\
                       else max_flow[path[i]][path[i+1]][1]
            flowArr.append(appendFlow)
            minFlow=min(flowArr)
        for i in range(len(path)-1):
            max_flow[path[i]][path[i+1]][1]=max_flow[path[i]][path[i+1]][1]+minFlow

In [20]:
max_net_flow(MaxFlow)

(5.0,
 {(0, 1, 2.0),
  (0, 2, 3.0),
  (1, 3, 2.0),
  (2, 1, 0.0),
  (2, 4, 3.0),
  (3, 2, 0.0),
  (3, 4, 0.0),
  (3, 5, 2.0),
  (4, 5, 3.0)})

In [21]:
#例31.5

In [22]:
#先求出网络最大流
flow=np.zeros((4,5,2))
flow[0][1][0]=4
flow[0][2][0]=1
flow[2][1][0]=2
flow[1][3][0]=6
flow[1][4][0]=1
flow[2][3][0]=3
flow[3][4][0]=2
f,s=max_net_flow(flow)
f

3.0

In [23]:
#用线性规划的方法求最小费用最大流
import pulp
x=[pulp.LpVariable(f'x{i}',lowBound=0,cat='Integer') for i in range(7)]
c=[10,8,2,7,5,10,4]
#[(0,1),(0,2),(1,3),(1,4),(2,1),(2,3)(3,4)]
m=pulp.LpProblem()
m+=pulp.lpDot(x,c)
m+=(x[0]+x[1]==3)
m+=(x[0]+x[4]==x[2]+x[3])
m+=(x[1]==x[4]+x[5])
m+=(x[5]+x[2]==x[6])
m+=(x[3]+x[6]==3)
m+=(x[0]<=4)
m+=(x[1]<=1)
m+=(x[2]<=6)
m+=(x[3]<=1)
m+=(x[4]<=2)
m+=(x[5]<=3)
m+=(x[6]<=2)
m.solve()
print(pulp.value(m.objective))
print([pulp.value(var) for var in x])

49.0
[3.0, 0.0, 2.0, 1.0, 0.0, 0.0, 2.0]
