In [1]:
import numpy as np
from numpy.linalg import *

In [2]:
#例8.3

In [3]:
A=np.array([[1,2,3],[4,5,6]])
#获得A的行列数
A.shape

(2, 3)

In [4]:
#例8.4

In [5]:
A=np.array([[-2,4],[1,-2]])
B=np.array([[2,4],[-3,-6]])
#矩阵乘法的两种方法
print('{}\n\n{}\n\n{}\n\n{}'.format(A@B,B@A,np.dot(A,B),np.dot(B,A)))

[[-16 -32]
 [  8  16]]

[[0 0]
 [0 0]]

[[-16 -32]
 [  8  16]]

[[0 0]
 [0 0]]


In [6]:
#A*B仅是对应元素相乘，没有线性代数方面的意义
A*B

array([[-4, 16],
       [-3, 12]])

In [7]:
#转换为矩阵后可以使用*
np.matrix(A)*np.matrix(B)

matrix([[-16, -32],
        [  8,  16]])

In [8]:
print(A@A@A)
#计算方阵的幂
print(matrix_power(A,3))

[[-32  64]
 [ 16 -32]]
[[-32  64]
 [ 16 -32]]


In [9]:
#例8.5

In [10]:
A=[[2,0,-1],[1,3,2]]
B=[[1,7,-1],[4,2,3],[2,0,1]]
#注意，直接对列表A、B进行A@B运算不合法
C=np.array(A)@np.array(B)
#C的转置 
C.T

array([[ 0, 17],
       [14, 13],
       [-3, 10]])

In [11]:
#4阶单位矩阵
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
#type(A)获得一个对象A的类型
type(np.matrix(np.eye(4)))

numpy.matrix

In [13]:
#例8.6

In [14]:
A=[[1,2,3],[2,2,1],[3,4,3]]
A=np.array(A)
#求一个矩阵的逆
inv(A)

array([[ 1. ,  3. , -2. ],
       [-1.5, -3. ,  2.5],
       [ 1. ,  1. , -1. ]])

In [15]:
#求矩阵的伴随
print('A* is:\n{}'.format(det(A)*inv(A)))

A* is:
[[ 2.  6. -4.]
 [-3. -6.  5.]
 [ 2.  2. -2.]]


In [16]:
#例8.7

In [24]:
A=np.array([[1,-1,-1],
            [2,-1,-3],
            [3,2,-5]])
b=np.array([2,1,0])
#求非齐次线性方程组
s=solve(A,b)
np.round(s,3)

array([ 5., -0.,  3.])