In [1]:
import numpy as np 
from numpy.linalg import eig

In [2]:
#例8.11

In [3]:
A=np.array([[-1,1,0],[-4,3,0],[1,0,2]])
#eig(A)函数返回一个方阵A的特征值及对应的特征向量
v,f=eig(A)
print(v)
print(f)

[2. 1. 1.]
[[ 0.          0.40824829  0.40824829]
 [ 0.          0.81649658  0.81649658]
 [ 1.         -0.40824829 -0.40824829]]


In [4]:
#方阵的迹：特征值的和，同是也是主对角线的和
np.trace(A)

4

In [5]:
#例8.12

In [6]:
from numpy.linalg import matrix_power,inv
A=np.array([[2,-1],[-1,2]])
matrix_power(A,10)

array([[ 29525, -29524],
       [-29524,  29525]])

In [7]:
v,f=eig(A)
diagA=np.diag(v)
f@matrix_power(diagA,10)@inv(f)

array([[ 29525., -29524.],
       [-29524.,  29525.]])