In [1]:
#例19.10

In [2]:
from scipy.stats import t
import numpy as np
X=np.array([506,508,499,503,504,510,497,512,\
            514,505,493,496,506,502,509,496])

#定义函数求置信上下限
def t_conf(data,confidence=0.95):
    #样本均值
    sample_mean = np.mean(data)  
    #样本标准差
    sample_std=np.std(data,ddof=1) 
    #样本容量
    sample_size = len(data)
    #显著性水平
    alpha = 1 - confidence 
    #t分布的分位数 
    t_score = t.isf(alpha/2,df=sample_size-1)  
    ME = sample_std / np.sqrt(sample_size) * t_score
    #置信下限
    lower_limit = sample_mean - ME
    #置信上限
    upper_limit = sample_mean + ME
    return lower_limit, upper_limit

lower_limit,upper_limit=t_conf(X)
print('({0:.2f},{1:.2f})'.format(lower_limit, upper_limit))

(500.45,507.05)


In [3]:
#例19.11

In [4]:
from scipy.stats import chi2
X=np.array([506,508,499,503,504,510,497,512,\
            514,505,493,496,506,502,509,496])

#定义函数求置信上下限
def chi2_conf(data,confidence=0.95):
    #样本方差
    sample_var=np.var(data,ddof=1) 
    #样本容量
    sample_size=len(data)
    #显著性水平
    alpha=1-confidence  
    #chi2分布的分位数(两侧)
    chi2_lscore=chi2.isf(1-alpha/2,sample_size-1)  
    chi2_rscore=chi2.isf(alpha/2,sample_size-1)
    #总体方差的置信上下限
    lower_limit=((sample_size-1)*sample_var)/chi2_rscore
    upper_limit=((sample_size-1)*sample_var)/chi2_lscore
    return lower_limit,upper_limit

lower_limit,upper_limit=chi2_conf(X)
print('({0:.2f},{1:.2f})'.format(np.sqrt(lower_limit),\
                                 np.sqrt(upper_limit)))

(4.58,9.60)


In [5]:
#例19.12

In [6]:
#两样本均值
meanX1,meanX2=500,496
#两样本标准差
S1,S2=1.1,1.2
#两样本容量
n1,n2=10,20
#显著性水平
alpha=0.05
#t分布的分位数 
t_score = t.isf(alpha/2,df=n1+n2-2)  
Sw=np.sqrt(((n1-1)*S1**2+(n2-1)*S2**2)/(n1+n2-2))
ME = Sw*np.sqrt(1/n1+1/n2)*t_score
#置信上下限
lower_limit = meanX1-meanX2 - ME
upper_limit = meanX1-meanX2 + ME
np.round([lower_limit, upper_limit],3)

array([3.073, 4.927])

In [7]:
#例19.13

In [8]:
meanX1,meanX2=91.73,93.75
S1_2,S2_2=3.89,4.02
n1,n2=8,8
alpha=0.05
t_score = t.isf(alpha/2,df=n1+n2-2)  
Sw=np.sqrt(((n1-1)*S1_2+(n2-1)*S2_2)/(n1+n2-2))
ME = Sw*np.sqrt(1/n1+1/n2)* t_score
lower_limit = meanX1-meanX2 - ME
upper_limit = meanX1-meanX2 + ME
np.round([lower_limit, upper_limit],3)

array([-4.153,  0.113])

In [9]:
#例19.14

In [10]:
from scipy.stats import f
#两样本容量
n1,n2=18,13
#两样本方差
S1_2,S2_2=0.34,0.29
#显著性水平
alpha=0.1
#f分布的分位数(两侧)
f_lscore=f.isf(1-alpha/2,n1-1,n2-1)  
f_rscore=f.isf(alpha/2,n1-1,n2-1)
#置信上下限
lower_limit=S1_2/S2_2/f_rscore
upper_limit=S1_2/S2_2/f_lscore
np.round([lower_limit, upper_limit],3)

array([0.454, 2.791])