In [1]:
import numpy as np
a=[-1,0,1]
np.cov(a),np.cov(a,bias=True),np.var(a)

(array(1.), array(0.66666667), 0.6666666666666666)

In [2]:
np.cov(a,ddof=0)

array(0.66666667)

In [3]:
import numpy as np
x=np.arange(1,11)
y=-2*x+1
np.cov(x,y,bias=True)

array([[  8.25, -16.5 ],
       [-16.5 ,  33.  ]])

In [4]:
import numpy as np
x=np.arange(1,11)
y=-2*x+1
#x与y的垂直拼接
a=np.vstack((x,y)) 
np.cov(a,bias=True)

array([[  8.25, -16.5 ],
       [-16.5 ,  33.  ]])

In [5]:
var_X=np.var(x)
var_Y=np.var(y)
cov_XY=np.mean((x-np.mean(x))*(y-np.mean(y)))
var_X,cov_XY,var_Y

(8.25, -16.5, 33.0)

In [6]:
import numpy as np
x=np.arange(1,11)
y=-2*x+1
np.corrcoef(x,y)

array([[ 1., -1.],
       [-1.,  1.]])

In [7]:
import numpy as np
x=np.arange(1,11)
y=-2*x+1
#x与y的垂直拼接
np.corrcoef(np.vstack((x,y)))

array([[ 1., -1.],
       [-1.,  1.]])

In [8]:
import numpy as np
from scipy.stats import uniform,expon,norm
rand_numers=1000
np.random.seed(0)
u=uniform().rvs(size=rand_numers)  #服从[0,1]均匀分布
v=expon().rvs(size=rand_numers)  #服从参数为1的指数分布
w=norm().rvs(size=rand_numers)  #服从标准正态分布
np.cov(np.vstack((u,v,w)),bias=True)

array([[ 8.44476867e-02, -5.39555598e-04, -6.35486006e-03],
       [-5.39555598e-04,  1.13730658e+00, -5.10737061e-02],
       [-6.35486006e-03, -5.10737061e-02,  9.47279857e-01]])

In [9]:
np.corrcoef(np.vstack((u,v,w)))

array([[ 1.        , -0.00174102, -0.02246844],
       [-0.00174102,  1.        , -0.04920616],
       [-0.02246844, -0.04920616,  1.        ]])

In [10]:
#将上一节的两个自定义函数复制过来,为了帮助读者理解相关系数矩阵的含义(协方差矩阵类似)，
#并将第二个函数的返回值保留小数点后8位:

In [11]:
def covariance(x,y):
    return np.mean((x-np.mean(x))*(y-np.mean(y)))
def corr_coef(x,y):
    return np.round(covariance(x,y)/np.var(x)**.5/np.var(y)**.5,8)

In [12]:
corr_coef(u,v),corr_coef(v,w),corr_coef(u,w),corr_coef(v,v)

(-0.00174102, -0.04920616, -0.02246844, 1.0)